#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 26 22:18:55 2020

@author: Mau
"""

from pandas import Series, DataFrame
import pandas as pd

df=pd.read_csv("/Users/-/Documents/_UTMSBA2021/1.2 Data Analytics Programming/Week2/NYC_Restaurants.csv", dtype=str)

#Q1: Create a unique name for each restaurant.
df["RESTAURANT"] = df["DBA"]+" "+df["BUILDING"]+" "+df["STREET"]+" "+df["ZIPCODE"]+" "+df["BORO"]
df["RESTAURANT"].iloc[:10]

#Q2: How many restaurants are included in the data?
len(df["RESTAURANT"].unique()) #10114

#Q3: How many chains are there?
vc = df[["DBA","RESTAURANT"]].drop_duplicates()["DBA"].value_counts()
len(vc[vc>1]) #368

#Q4: Plot a bar graph of the top 20 most popular chains.
df[["DBA","RESTAURANT"]].drop_duplicates()["DBA"].value_counts()[:10].plot(kind="bar")

#Q5: What fraction of all restaurants are chain restaurants? (?)
rn = len(df["RESTAURANT"].unique())
ch = vc[vc>1]
chn = len(ch)
chn/rn #3.6%

#Q6: Plot the number of non-chain restaurants in each boro.
df["chain"]=df["DBA"].isin(ch.index)
mask = df["chain"] == False
df2 = df[mask]
df2[["RESTAURANT","BORO"]].drop_duplicates()["BORO"].value_counts()[:5].plot(kind="bar")
# Manhattan is the one with more independent restaurants

#Q7: Plot the fraction of non-chain restaurants in each boro.
fraction = df2[["RESTAURANT","BORO"]].drop_duplicates()["BORO"].value_counts()/df[["RESTAURANT","BORO"]].drop_duplicates()["BORO"].value_counts()
fraction[:5].plot(kind="bar")
#No. Brooklyn is the one with higest independet ratio


#Q8: Plot the popularity of cuisines.
df[["CUISINE DESCRIPTION","RESTAURANT"]].drop_duplicates()["CUISINE DESCRIPTION"].value_counts()[:20].plot(kind="bar")

#Q9: Plot the cuisines among restaurants which never got cited for violations.
maskClean = df["VIOLATION CODE"].isnull()
dfClean = df[maskClean]
dfClean[["RESTAURANT","CUISINE DESCRIPTION"]].drop_duplicates()["CUISINE DESCRIPTION"].value_counts()[:20].plot(kind="bar")

#Q10: What cuisines tend to be the “cleanest”?
top20=df[["RESTAURANT","CUISINE DESCRIPTION"]].drop_duplicates()["CUISINE DESCRIPTION"].value_counts() >20
popularity = df[["CUISINE DESCRIPTION","RESTAURANT"]].drop_duplicates()["CUISINE DESCRIPTION"].value_counts()
cleanCuisines = dfClean[["RESTAURANT","CUISINE DESCRIPTION"]].drop_duplicates()["CUISINE DESCRIPTION"].value_counts()
ratio=cleanCuisines[top20]/popularity[top20]
ratio.sort_values(ascending=False)[:10]

#Q11: What are the most common violations in each borough?



























